/*
=================================================
Project: Brazilian E-Commerce (Olist) Analysis
File: 05_product_analysis.sql
=================================================
purpose:
analyze product performance, category trends,
pricing, sales, and customer satisfaction to
identify top-performing products and support
inventory and marketing decisions.
Dataset:
    Olist Brazilian E-Commerce Public Dataset
=================================================
*/



/*
=================================================
1. product overview
=================================================
purpose:
understand the overall product catalog, category
distribution, and product availability across the
marketplace.
=================================================
*/

/*
=================================================
1.1 total products
=================================================
*/

select

    count(*) as total_products

from olist_products_dataset;

/*
=================================================
1.2 total product categories
=================================================
*/

select

    count(distinct product_category_name) as total_categories

from olist_products_dataset;

/*
=================================================
1.3 products per category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as total_products

from olist_products_dataset p

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by category

order by total_products desc;

/*
=================================================
1.4 top 10 categories by number of products
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as total_products

from olist_products_dataset p

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by category

order by total_products desc

limit 10;

/*
=================================================
1.5 bottom 10 categories by number of products
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as total_products

from olist_products_dataset p

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by category

order by total_products

limit 10;

/*
=================================================
1.6 products without category
=================================================
*/

select

    count(*) as products_without_category

from olist_products_dataset

where product_category_name is null;

/*
=================================================
1.7 executive summary
=================================================
*/

select

    count(*) as total_products,

    count(distinct product_category_name) as total_categories,

    sum(

        case

            when product_category_name is null

            then 1

            else 0

        end

    ) as products_without_category

from olist_products_dataset;

/*
=================================================
observations
=================================================

1. the marketplace offers a diverse product catalog
across multiple product categories.

2. product distribution is uneven, with a few
categories containing a large share of all
products while others contain relatively few.

3. identifying the largest categories helps
prioritize inventory management, merchandising,
and marketing investments.

4. smaller categories may represent niche markets
or opportunities for product assortment expansion.

5. products without assigned categories should be
reviewed to improve data quality and ensure
accurate reporting.

=================================================
*/


--------


/*
=================================================
2. product revenue analysis
=================================================
purpose:
analyze revenue generated by individual products
to identify top-performing, low-performing, and
unsold products for inventory, marketing, and
pricing decisions.
=================================================
*/

/*
=================================================
2.1 revenue by product
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by total_revenue desc;

/*
=================================================
2.2 top 20 products by revenue
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by total_revenue desc

limit 20;

/*
=================================================
2.3 bottom 20 products by revenue
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by total_revenue

limit 20;

/*
=================================================
2.4 average revenue per product
=================================================
*/

with product_revenue as (

    select

        product_id,

        sum(price) as total_revenue

    from olist_order_items_dataset

    group by product_id

)

select

    round(avg(total_revenue),2) as average_revenue_per_product,

    round(min(total_revenue),2) as minimum_revenue,

    round(max(total_revenue),2) as maximum_revenue

from product_revenue;

/*
=================================================
2.5 revenue contribution by product
=================================================
*/

with product_revenue as (

    select

        product_id,

        sum(price) as total_revenue

    from olist_order_items_dataset

    group by product_id

)

select

    product_id,

    round(total_revenue,2) as total_revenue,

    round(

        total_revenue
        *100.0
        /sum(total_revenue) over(),

        2

    ) as revenue_percentage

from product_revenue

order by total_revenue desc;

/*
=================================================
2.6 products with no sales
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category

from olist_products_dataset p

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

left join olist_order_items_dataset oi
    on p.product_id = oi.product_id

where oi.product_id is null

order by category;

/*
=================================================
2.7 executive summary
=================================================
*/

with product_revenue as (

    select

        product_id,

        sum(price) as total_revenue

    from olist_order_items_dataset

    group by product_id

)

select

    count(*) as products_with_sales,

    round(sum(total_revenue),2) as total_revenue,

    round(avg(total_revenue),2) as average_revenue_per_product,

    round(max(total_revenue),2) as highest_product_revenue,

    round(min(total_revenue),2) as lowest_product_revenue

from product_revenue;
/*
=================================================
observations
=================================================

1. product revenue is highly concentrated, with a
small number of products generating a significant
share of total sales.

2. top-performing products should be prioritized
for inventory planning, promotions, and marketing
campaigns.

3. products generating little revenue may require
pricing adjustments, better visibility, or
discontinuation.

4. products with no sales represent inactive
inventory and should be reviewed to determine
whether they should be promoted or removed from
the catalog.

5. revenue contribution analysis helps identify
the products that have the greatest impact on
overall business performance.

=================================================
*/


--------


/*
=================================================
3. product sales analysis
=================================================
purpose:
analyze product sales volume and purchasing
patterns to identify high-demand products,
customer buying behavior, and inventory needs.
=================================================
*/


/*
=================================================
3.1 units sold by product
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as units_sold

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by units_sold desc;


/*
=================================================
3.2 top 20 best-selling products
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as units_sold

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by units_sold desc

limit 20;


/*
=================================================
3.3 bottom 20 products by units sold
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as units_sold

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by
    units_sold,
    p.product_id

limit 20;

/*
=================================================
3.4 orders containing each product
=================================================
*/

select

    p.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(distinct oi.order_id) as total_orders

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by
    p.product_id,
    category

order by total_orders desc;

/*
=================================================
3.5 average units per order
=================================================
*/

with order_quantity as (

    select

        order_id,

        count(*) as units

    from olist_order_items_dataset

    group by order_id

)

select

    round(avg(units),2) as average_units_per_order,

    min(units) as minimum_units,

    max(units) as maximum_units

from order_quantity;

/*
=================================================
3.6 product sales distribution
=================================================
*/

with product_sales as (

    select

        product_id,

        count(*) as units_sold

    from olist_order_items_dataset

    group by product_id

)

select

    case

        when units_sold = 1 then '1 Unit'

        when units_sold between 2 and 5 then '2-5 Units'

        when units_sold between 6 and 10 then '6-10 Units'

        when units_sold between 11 and 50 then '11-50 Units'

        when units_sold between 51 and 100 then '51-100 Units'

        else '100+ Units'

    end as sales_range,

    count(*) as products

from product_sales

group by sales_range

order by

case sales_range

    when '1 Unit' then 1
    when '2-5 Units' then 2
    when '6-10 Units' then 3
    when '11-50 Units' then 4
    when '51-100 Units' then 5
    else 6

end;

/*
=================================================
3.7 executive summary
=================================================
*/

with product_sales as (

    select

        product_id,

        count(*) as units_sold,

        count(distinct order_id) as total_orders

    from olist_order_items_dataset

    group by product_id

)

select

    count(*) as products_with_sales,

    sum(units_sold) as total_units_sold,

    round(avg(units_sold),2) as average_units_per_product,

    round(avg(total_orders),2) as average_orders_per_product,

    max(units_sold) as highest_units_sold,

    min(units_sold) as lowest_units_sold

from product_sales;
/*
=================================================
observations
=================================================

1. sales volume and revenue are not always aligned;
some products generate high revenue with low sales
volume, while others rely on high unit sales.

2. identifying best-selling products helps optimize
inventory levels and reduce stock-out risk.

3. products appearing in many orders indicate strong
customer demand and should receive priority in
procurement and replenishment.

4. average units per order provide insight into
customer purchasing behavior and basket size.

5. analyzing product sales distribution highlights
whether sales are concentrated among a few products
or spread across the catalog, supporting inventory
planning and assortment decisions.

=================================================
*/


--------


/*
=================================================
4. product category analysis
=================================================
purpose:
evaluate product category performance across
revenue, sales volume, pricing, and customer
demand to identify the marketplace's strongest
and weakest categories.
=================================================
*/


/*
=================================================
4.1 revenue by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by total_revenue desc;

/*
=================================================
4.2 units sold by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(*) as units_sold

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by units_sold desc;

/*
=================================================
4.3 orders by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    count(distinct oi.order_id) as total_orders

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by total_orders desc;

/*
=================================================
4.4 average selling price by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(avg(oi.price),2) as average_selling_price

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by average_selling_price desc;

/*
=================================================
4.5 average revenue per order by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(

        sum(oi.price)

        /

        count(distinct oi.order_id),

        2

    ) as average_revenue_per_order

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by average_revenue_per_order desc;

/*
=================================================
4.6 category revenue contribution
=================================================
*/

with category_revenue as (

    select

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        sum(oi.price) as total_revenue

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by category

)

select

    category,

    round(total_revenue,2) as total_revenue,

    round(

        total_revenue
        *100.0
        /sum(total_revenue) over(),

        2

    ) as revenue_percentage

from category_revenue

order by total_revenue desc;

/*
=================================================
4.7 top 10 categories
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by total_revenue desc

limit 10;

/*
=================================================
4.7 bottom 10 categories
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as total_revenue

from olist_order_items_dataset oi

join olist_products_dataset p
    on oi.product_id = p.product_id

left join product_category_name_translation pct
    on p.product_category_name = pct.product_category_name

group by category

order by total_revenue

limit 10;

/*
=================================================
4.8 executive summary
=================================================
*/

with category_summary as (

    select

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        sum(oi.price) as revenue,

        count(*) as units_sold,

        count(distinct oi.order_id) as total_orders

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by category

)

select

    count(*) as total_categories,

    round(sum(revenue),2) as total_revenue,

    round(avg(revenue),2) as average_category_revenue,

    round(avg(units_sold),2) as average_units_sold,

    round(avg(total_orders),2) as average_orders

from category_summary;
/*
=================================================
observations
=================================================

1. category performance varies significantly across
the marketplace, with a small number of categories
generating a large share of total revenue.

2. high-revenue categories should receive priority
for inventory investment, marketing campaigns,
and supplier negotiations.

3. comparing units sold and average selling price
helps distinguish high-volume categories from
premium-priced categories.

4. average revenue per order highlights categories
that contribute the greatest value to each
customer purchase.

5. revenue contribution analysis identifies the
categories that drive overall business performance
and supports strategic portfolio management.

=================================================
*/


--------


/*
=================================================
5. product pricing analysis
=================================================
purpose:
analyze product pricing patterns across the
marketplace to identify premium categories,
budget-friendly products, and pricing
distribution.
=================================================
*/


/*
=================================================
5.1 overall price statistics
=================================================
*/

select

    round(avg(price),2) as average_price,

    round(min(price),2) as minimum_price,

    round(max(price),2) as maximum_price,

    round(stddev(price),2) as price_std_dev

from olist_order_items_dataset;

/*
=================================================
5.2 price distribution
=================================================
*/

select

    case

        when price < 50 then 'Under $50'

        when price < 100 then '$50 - $99'

        when price < 200 then '$100 - $199'

        when price < 500 then '$200 - $499'

        when price < 1000 then '$500 - $999'

        else '$1000+'

    end as price_range,

    count(*) as products,

    round(sum(price),2) as revenue

from olist_order_items_dataset

group by price_range

order by

case price_range

    when 'Under $50' then 1
    when '$50 - $99' then 2
    when '$100 - $199' then 3
    when '$200 - $499' then 4
    when '$500 - $999' then 5
    else 6

end;

/*
=================================================
5.3 average price by category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(avg(oi.price),2) as average_price

from olist_order_items_dataset oi

join olist_products_dataset p

on oi.product_id=p.product_id

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by category

order by average_price desc;

/*
=================================================
5.4 highest priced products
=================================================
*/

select

    oi.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    max(oi.price) as highest_price

from olist_order_items_dataset oi

join olist_products_dataset p

on oi.product_id=p.product_id

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by
    oi.product_id,
    category

order by highest_price desc

limit 20;

/*
=================================================
5.4 lowest priced products
=================================================
*/

select

    oi.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    min(oi.price) as lowest_price

from olist_order_items_dataset oi

join olist_products_dataset p

on oi.product_id=p.product_id

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by
    oi.product_id,
    category

order by lowest_price

limit 20;

/*
=================================================
5.5 price range analysis
=================================================
*/

select

    case

        when price < 50 then 'Budget'

        when price between 50 and 200 then 'Mid Range'

        when price between 200 and 500 then 'Premium'

        else 'Luxury'

    end as price_segment,

    count(*) as units_sold,

    round(sum(price),2) as revenue,

    round(avg(price),2) as average_price

from olist_order_items_dataset

group by price_segment

order by average_price;

/*
=================================================
5.6 premium vs budget products
=================================================
*/

select

    case

        when price >= 200 then 'Premium'

        else 'Budget'

    end as product_type,

    count(*) as units_sold,

    round(sum(price),2) as revenue,

    round(avg(price),2) as average_price

from olist_order_items_dataset

group by product_type;

/*
=================================================
5.7 executive summary
=================================================
*/

select

    round(avg(price),2) as average_price,

    round(min(price),2) as minimum_price,

    round(max(price),2) as maximum_price,

    count(*) as total_items_sold,

    round(sum(price),2) as total_revenue

from olist_order_items_dataset;
/*
=================================================
observations
=================================================

1. product prices vary widely across the marketplace,
indicating a mix of budget, mid-range, premium,
and luxury products.

2. category-level pricing helps identify premium
segments that generate higher revenue per sale.

3. price distribution reveals whether the business
focuses primarily on affordable products or
higher-value items.

4. comparing revenue across price ranges helps
determine whether business growth is driven by
high-priced products or high sales volume.

5. understanding pricing patterns supports pricing
strategy, promotional planning, and product
positioning.

=================================================
*/


--------


/*
=================================================
6. product performance ranking
=================================================
purpose:
rank products and product categories using
revenue, sales volume, and overall performance
metrics to identify the marketplace's strongest
and weakest performers.
=================================================
*/

/*
=================================================
6.1 revenue ranking
=================================================
*/

with product_revenue as (

    select

        oi.product_id,

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        round(sum(oi.price),2) as revenue

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by
        oi.product_id,
        category

)

select

    product_id,

    category,

    revenue,

    rank() over(
        order by revenue desc
    ) as revenue_rank

from product_revenue

order by revenue_rank;

/*
=================================================
6.2 sales volume ranking
=================================================
*/

with product_sales as (

    select

        oi.product_id,

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        count(*) as units_sold

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by
        oi.product_id,
        category

)

select

    product_id,

    category,

    units_sold,

    rank() over(
        order by units_sold desc
    ) as sales_rank

from product_sales

order by sales_rank;

/*
=================================================
6.3 category revenue ranking
=================================================
*/

with category_revenue as (

    select

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        round(sum(oi.price),2) as revenue

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by category

)

select

    category,

    revenue,

    dense_rank() over(
        order by revenue desc
    ) as category_rank

from category_revenue

order by category_rank;

/*
=================================================
6.4 top 10 products within each category
=================================================
*/

with product_revenue as (

    select

        oi.product_id,

        coalesce(
            pct.product_category_name_english,
            'Unknown'
        ) as category,

        round(sum(oi.price),2) as revenue

    from olist_order_items_dataset oi

    join olist_products_dataset p
        on oi.product_id = p.product_id

    left join product_category_name_translation pct
        on p.product_category_name = pct.product_category_name

    group by
        oi.product_id,
        category

)

select *

from (

    select

        *,

        row_number() over(

            partition by category

            order by revenue desc

        ) as rn

    from product_revenue

) ranked

where rn<=10

order by
category,
rn;

/*
=================================================
6.5 product performance score
=================================================
*/

with performance as (

    select

        oi.product_id,

        round(sum(oi.price),2) as revenue,

        count(*) as units_sold,

        count(distinct oi.order_id) as orders_count

    from olist_order_items_dataset oi

    group by oi.product_id

)

select

    *,

    ntile(5) over(order by revenue desc) as revenue_score,

    ntile(5) over(order by units_sold desc) as sales_score,

    ntile(5) over(order by orders_count desc) as order_score,

    (

        ntile(5) over(order by revenue desc)

        +

        ntile(5) over(order by units_sold desc)

        +

        ntile(5) over(order by orders_count desc)

    ) as performance_score

from performance

order by performance_score desc;

/*
=================================================
6.6 top 20 overall products
=================================================
*/

with performance as (

    select

        product_id,

        sum(price) as revenue,

        count(*) as units_sold

    from olist_order_items_dataset

    group by product_id

)

select *

from performance

order by
revenue desc,
units_sold desc

limit 20;

/*
=================================================
6.7 bottom 20 overall products
=================================================
*/

with performance as (

    select

        product_id,

        sum(price) as revenue,

        count(*) as units_sold

    from olist_order_items_dataset

    group by product_id

)

select *

from performance

order by
revenue,
units_sold

limit 20;

/*
=================================================
6.8 executive summary
=================================================
*/

with performance as (

    select

        product_id,

        sum(price) as revenue,

        count(*) as units_sold,

        count(distinct order_id) as total_orders

    from olist_order_items_dataset

    group by product_id

)

select

    count(*) as products_with_sales,

    round(avg(revenue),2) as average_revenue,

    round(avg(units_sold),2) as average_units_sold,

    round(avg(total_orders),2) as average_orders,

    max(revenue) as highest_product_revenue,

    max(units_sold) as highest_units_sold

from performance;
/*
=================================================
observation
=================================================

1. Ranking products across multiple metrics provides
a more complete picture than revenue alone.

2. Products that consistently rank highly in revenue,
sales volume, and order frequency should be
prioritized for inventory, marketing, and retention.

3. The Product Performance Matrix helps distinguish
between products that are profitable, popular, or
underperforming, supporting strategic product
portfolio decisions.

4. Combining window functions with business
classification demonstrates advanced SQL and
analytical skills suitable for real-world reporting.
=================================================
*/


--------


/*
=================================================
7. product lifecycle analysis
=================================================
purpose:
analyze product performance over time to identify
growth trends, seasonal demand, consistent
performers, and declining products.
=================================================
*/


/*
=================================================
7.1 monthly product revenue
=================================================
*/

select

    date_format(o.order_purchase_timestamp,'%Y-%m') as sales_month,

    oi.product_id,

    round(sum(oi.price),2) as revenue

from olist_orders_dataset o

join olist_order_items_dataset oi
    on o.order_id = oi.order_id

where o.order_status='delivered'

group by
    sales_month,
    oi.product_id

order by
    sales_month,
    revenue desc;
    
/*
=================================================
7.2 monthly units sold
=================================================
*/

select

    date_format(o.order_purchase_timestamp,'%Y-%m') as sales_month,

    oi.product_id,

    count(*) as units_sold

from olist_orders_dataset o

join olist_order_items_dataset oi
    on o.order_id = oi.order_id

where o.order_status='delivered'

group by
    sales_month,
    oi.product_id

order by
    sales_month,
    units_sold desc;
    
/*
=================================================
7.3 month-over-month product growth
=================================================
*/

with monthly_revenue as (

    select

        date_format(o.order_purchase_timestamp,'%Y-%m') as sales_month,

        oi.product_id,

        sum(oi.price) as revenue

    from olist_orders_dataset o

    join olist_order_items_dataset oi
        on o.order_id = oi.order_id

    where o.order_status='delivered'

    group by
        sales_month,
        oi.product_id

)

select

    sales_month,

    product_id,

    round(revenue,2) as revenue,

    round(

        lag(revenue) over(
            partition by product_id
            order by sales_month
        ),

        2

    ) as previous_month,

    round(

        revenue
        -

        lag(revenue) over(
            partition by product_id
            order by sales_month
        ),

        2

    ) as revenue_change

from monthly_revenue

order by
product_id,
sales_month;

/*
=================================================
7.4 product sales trend
=================================================
*/

with monthly_sales as (

    select

        oi.product_id,

        date_format(o.order_purchase_timestamp,'%Y-%m') as sales_month,

        count(*) as units_sold

    from olist_orders_dataset o

    join olist_order_items_dataset oi
        on o.order_id=oi.order_id

    where o.order_status='delivered'

    group by
        oi.product_id,
        sales_month

)

select

    product_id,

    count(*) as active_months,

    round(avg(units_sold),2) as average_monthly_sales,

    max(units_sold) as peak_monthly_sales

from monthly_sales

group by product_id

order by average_monthly_sales desc;

/*
=================================================
7.5 consistently selling products
=================================================
*/

select

    oi.product_id,

    count(

        distinct date_format(
            o.order_purchase_timestamp,
            '%Y-%m'
        )

    ) as active_months,

    count(*) as units_sold

from olist_orders_dataset o

join olist_order_items_dataset oi
    on o.order_id=oi.order_id

where o.order_status='delivered'

group by oi.product_id

order by
active_months desc,
units_sold desc

limit 20;

/*
=================================================
7.6 seasonal products
=================================================
*/

with monthly_sales as (

    select

        oi.product_id,

        month(o.order_purchase_timestamp) as sales_month,

        count(*) as units_sold

    from olist_orders_dataset o

    join olist_order_items_dataset oi
        on o.order_id=oi.order_id

    where o.order_status='delivered'

    group by
        oi.product_id,
        sales_month

)

select

    product_id,

    max(units_sold) as peak_month_sales,

    min(units_sold) as lowest_month_sales,

    round(stddev(units_sold),2) as monthly_variation

from monthly_sales

group by product_id

having monthly_variation > 5

order by monthly_variation desc;

/*
=================================================
7.7 declining products
=================================================
*/

with monthly_sales as (

    select

        oi.product_id,

        date_format(
            o.order_purchase_timestamp,
            '%Y-%m'
        ) as sales_month,

        count(*) as units_sold

    from olist_orders_dataset o

    join olist_order_items_dataset oi
        on o.order_id=oi.order_id

    where o.order_status='delivered'

    group by
        oi.product_id,
        sales_month

),

ranked as (

    select

        *,

        row_number() over(

            partition by product_id

            order by sales_month

        ) as first_month,

        row_number() over(

            partition by product_id

            order by sales_month desc

        ) as last_month

    from monthly_sales

)

select

    f.product_id,

    f.units_sold as first_month_sales,

    l.units_sold as last_month_sales,

    l.units_sold - f.units_sold as sales_change

from ranked f

join ranked l

on f.product_id=l.product_id

where
f.first_month=1
and
l.last_month=1

order by sales_change;

/*
=================================================
7.8 executive summary
=================================================
*/

with monthly_sales as (

    select

        oi.product_id,

        date_format(
            o.order_purchase_timestamp,
            '%Y-%m'
        ) as sales_month,

        sum(oi.price) as revenue,

        count(*) as units_sold

    from olist_orders_dataset o

    join olist_order_items_dataset oi
        on o.order_id=oi.order_id

    where o.order_status='delivered'

    group by
        oi.product_id,
        sales_month

)

select

    count(distinct product_id) as active_products,

    count(distinct sales_month) as business_months,

    round(avg(revenue),2) as average_monthly_revenue,

    round(avg(units_sold),2) as average_monthly_units

from monthly_sales;
/*
=================================================
observation
=================================================

1. Lifecycle analysis reveals how product demand
changes over time rather than relying on total
historical performance.

2. Month-over-month growth highlights products that
are gaining momentum as well as those losing
customer interest.

3. Consistently selling products provide stable
revenue and should be prioritized for inventory
planning.

4. Seasonal and declining products require different
business strategies, such as promotional campaigns,
seasonal stocking, or product replacement.

5. Time-based analysis transforms static sales
reports into forward-looking business insights,
making this section valuable for forecasting and
strategic planning.

=================================================
*/


--------


/*
=================================================
8. executive summary
=================================================
purpose:
provide a high-level summary of the product
portfolio by combining the most important
performance metrics into an executive report.
=================================================
*/


/*
=================================================
8.1 product portfolio kpis
=================================================
*/

with product_summary as (

    select

        oi.product_id,

        sum(oi.price) as revenue,

        count(*) as units_sold,

        count(distinct oi.order_id) as total_orders

    from olist_order_items_dataset oi

    group by oi.product_id

)

select

    (select count(*) from olist_products_dataset) as total_products,

    (select count(distinct product_category_name)
     from olist_products_dataset) as total_categories,

    count(*) as products_with_sales,

    round(sum(revenue),2) as total_revenue,

    sum(units_sold) as total_units_sold,

    round(avg(revenue),2) as average_revenue_per_product,

    round(avg(units_sold),2) as average_units_per_product

from product_summary;

/*
=================================================
8.2 top performing product
=================================================
*/

select

    oi.product_id,

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as revenue,

    count(*) as units_sold,

    count(distinct oi.order_id) as total_orders

from olist_order_items_dataset oi

join olist_products_dataset p

on oi.product_id=p.product_id

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by
    oi.product_id,
    category

order by revenue desc

limit 1;

/*
=================================================
8.3 top performing category
=================================================
*/

select

    coalesce(
        pct.product_category_name_english,
        'Unknown'
    ) as category,

    round(sum(oi.price),2) as revenue,

    count(*) as units_sold,

    count(distinct oi.order_id) as total_orders

from olist_order_items_dataset oi

join olist_products_dataset p

on oi.product_id=p.product_id

left join product_category_name_translation pct

on p.product_category_name=pct.product_category_name

group by category

order by revenue desc

limit 1;

/*
=================================================
8.4 pricing summary
=================================================
*/

select

    round(avg(price),2) as average_price,

    round(min(price),2) as minimum_price,

    round(max(price),2) as maximum_price,

    round(stddev(price),2) as price_standard_deviation

from olist_order_items_dataset;

/*
=================================================
8.5 product performance distribution
=================================================
*/

with performance as (

    select

        product_id,

        sum(price) as revenue

    from olist_order_items_dataset

    group by product_id

)

select

    case

        when revenue < 100 then 'Under $100'

        when revenue < 500 then '$100-$499'

        when revenue < 1000 then '$500-$999'

        when revenue < 5000 then '$1K-$5K'

        else 'Over $5K'

    end as revenue_band,

    count(*) as products

from performance

group by revenue_band

order by

case revenue_band

    when 'Under $100' then 1
    when '$100-$499' then 2
    when '$500-$999' then 3
    when '$1K-$5K' then 4
    else 5

end;

/*
=================================================
8.6 business recommendations
=================================================

1. prioritize inventory investment in the
highest-revenue and best-selling products to
maximize sales and minimize stock-outs.

2. increase marketing efforts for high-performing
product categories, as they contribute the largest
share of marketplace revenue.

3. review low-performing and no-sale products to
determine whether they should be promoted,
repriced, or removed from the catalog.

4. use pricing analysis to balance premium and
budget product offerings while maintaining
competitiveness and profitability.

5. monitor seasonal and lifecycle trends to improve
inventory planning, demand forecasting, and
promotional timing.

6. regularly review product performance rankings to
identify emerging best sellers and declining
products, enabling proactive business decisions.

=================================================
*/


/*
=================================================
OBSERVATION
=================================================

1. Product analysis provides a complete view of the
marketplace's catalog, covering revenue, sales,
pricing, category performance, and lifecycle trends.

2. Combining multiple performance metrics helps
identify products that drive business growth as well
as those that require strategic intervention.

3. Product segmentation supports data-driven
decisions for pricing, inventory management,
marketing campaigns, and product portfolio
optimization.

4. The Executive Product Scorecard consolidates
operational and financial metrics into a single,
actionable report suitable for executive dashboards.

=================================================
*/
